// Automatically generated by flapigen
package com.example.audiorecorder.lib;

/**
 * Sine-wave generator stream
 */
public final class AudioSineWaveGen {

    public AudioSineWaveGen() {
        mNativeObj = init();
    }
    private static native long init();
    /**
     * Create and start audio stream
     */
    public final void tryStart() {
        do_tryStart(mNativeObj);
    }
    private static native void do_tryStart(long self);
    /**
     * Pause audio stream
     */
    public final void tryPause() {
        do_tryPause(mNativeObj);
    }
    private static native void do_tryPause(long self);
    /**
     * Stop and remove audio stream
     */
    public final void tryStop() {
        do_tryStop(mNativeObj);
    }
    private static native void do_tryStop(long self);
    /**
     * Print device's audio info
     */
    public static native void audioProbe();

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ AudioSineWaveGen(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}